section: screens
	Mactop:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	archlinux:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	Mactop:
		right = archlinux
	archlinux:
		left = Mactop
end

section: options
	protocol = barrier
	relativeMouseMoves = false
	win32KeepForeground = false
	defaultLockToScreenState = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 3072
	switchCorners = none 
	switchCornerSize = 0
end

