foreground              #FFFFFF
background              #11151A
selection_foreground    #11151A
selection_background    #FFFFFF
cursor                  #AC8986
cursor_text_color       #101111

active_tab_foreground     #11151A
active_tab_background     #575259
inactive_tab_foreground   #575259
inactive_tab_background   #11151A

# black
color0      #293B52
color8      #57708F

# red
color1      #FFD0CC
color9      #F0B0AA

# green
color2      #CCE0FF
color10     #AAC6F0

# yellow
color3      #F0CCFF
color11     #DCAAF0

# blue
color4      #9ABBE6
color12     #9ABBE6

# magenta
color5      #9AB8E6
color13     #9AB8E6

# cyan
color6      #D09AE6
color14     #D09AE6

# white
color7      #FFD0CC
color15     #F0B0AA
