[FileDialog]
history=file:///home/autometalogolex/Emulation/roms/ps3/Minecraft_Story_Mode_The_Complete_Adventure_USA_PS3-CLANDESTiNE-NewzTown/BLUS31606/PS3_GAME, file:///home/autometalogolex/Emulation/roms/ps4, file:///home/autometalogolex/.local/share/shadPS4, file:///home/autometalogolex/Applications, file:///home/autometalogolex, file:///home/autometalogolex/Config-Files/EmuDeck/backend
lastVisited=file:///home/autometalogolex/Config-Files/EmuDeck/backend
qtVersion=6.10.0
shortcuts=file:///home/autometalogolex/Documents, file:///home/autometalogolex/Desktop, file:///home/autometalogolex, file:///home/autometalogolex/Downloads, file:mods
sidebarWidth=91
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xa5\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xe1\0\0\0\x1\0\0\0\0\0\0\0\x35\0\0\0\x1\0\0\0\0\0\0\0\x35\0\0\0\x1\0\0\0\0\0\0\0Z\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
