[colors]
background = "#453821F0"
text_primary = "#f3f2f2FF"
text_muted = "#b6b4afFF"
accent_primary = "#e4b867FF"
accent_secondary = "#c4d65cFF"
warning = "#8acc66FF"
error = "#fd4663FF"

[appearance]
border_focused = "#e4b867FF"
border_unfocused = "#372d1bFF"
scratchpad_border_focused = "#8acc66FF"
scratchpad_border_unfocused = "#35641bFF"
outer_border_color = "#292214FF"
insert_hint_color = "#8acc6680"
backdrop_color = "#372d1bFF"

[overview]
background_tint = "#29221488"
