[colors]
background = "#2a343cF0"
text_primary = "#f2f2f3FF"
text_muted = "#afb3b6FF"
accent_primary = "#67a9e4FF"
accent_secondary = "#6266d8FF"
warning = "#9a6cceFF"
error = "#fd4663FF"

[appearance]
border_focused = "#67a9e4FF"
border_unfocused = "#222930FF"
scratchpad_border_focused = "#9a6cceFF"
scratchpad_border_unfocused = "#411d6bFF"
outer_border_color = "#191f24FF"
insert_hint_color = "#9a6cce80"
backdrop_color = "#222930FF"

[overview]
background_tint = "#191f2488"
