$primary            = rgb(#ffb59e)
$onPrimary          = rgb(#561f0e)
$primaryContainer   = rgb(#723522)
$onPrimaryContainer = rgb(#ffdbd0)
$secondary          = rgb(#e7bdb1)
$surface            = rgb(#1a110f)
$onSurface          = rgb(#f1dfda)
$surfaceContainer   = rgb(#271d1b)
$outline            = rgb(#a08c87)
$background         = rgb(#1a110f)

# Hyprland border colors
$activeBorder       = rgb(#ffb59e)
$inactiveBorder     = rgb(#53433f)
