$primary            = rgb(#ecc06c)
$onPrimary          = rgb(#412d00)
$primaryContainer   = rgb(#5d4200)
$onPrimaryContainer = rgb(#ffdea5)
$secondary          = rgb(#d9c4a0)
$surface            = rgb(#17130b)
$onSurface          = rgb(#ebe1d4)
$surfaceContainer   = rgb(#241f17)
$outline            = rgb(#9a8f80)
$background         = rgb(#17130b)

# Hyprland border colors
$activeBorder       = rgb(#ecc06c)
$inactiveBorder     = rgb(#4e4639)
