$primary            = rgb(#ffb3b4)
$onPrimary          = rgb(#561d21)
$primaryContainer   = rgb(#733336)
$onPrimaryContainer = rgb(#ffdad9)
$secondary          = rgb(#e6bdbc)
$surface            = rgb(#1a1111)
$onSurface          = rgb(#f0dede)
$surfaceContainer   = rgb(#271d1d)
$outline            = rgb(#a08c8c)
$background         = rgb(#1a1111)

# Hyprland border colors
$activeBorder       = rgb(#ffb3b4)
$inactiveBorder     = rgb(#524343)
