#wallpaper {
# monitor = 
# path = /home/autometalogolex/Documents/Wallpapers/stormlight-archives-wallpaper-v2.png

#}
preload = ~/Documents/Wallpapers/Way-of-Kings.jpg
preload = ~/Documents/Wallpapers/Words-of-Radiance.jpg
preload = ~/Documents/Wallpapers/Oathbringer.jpg
preload = ~/Documents/Wallpapers/Rhythm-of-War.jpg
preload = ~/Documents/Wallpapers/Wind-and-Truth.jpg
preload = ~/Documents/Wallpapers/stormlight-archives-wallpaper-v2.png
wallpaper {
    monitor = DP-2
    path = ~/Documents/Wallpapers/Way-of-Kings.jpg
    fit_mode = cover
}
