-- Generated by HyprMod

-- Environment
hl.env("HYPRCURSOR_THEME", "Nordzy-hyprcursors-catppuccin-frappe-dark")
hl.env("HYPRCURSOR_SIZE", "24")

-- Settings
hl.config({
    cursor = {
        inactive_timeout = 5.0,
        no_warps = true,
        persistent_warps = true,
        warp_on_change_workspace = 0,
        zoom_factor = 1.0,
    },
    decoration = {
        blur = {
            enabled = true,
            ignore_opacity = true,
            size = 2,
            special = true,
            xray = false,
        },
        dim_inactive = true,
        dim_special = 0.2,
        fullscreen_opacity = 1.0,
        rounding_power = 2.0,
    },
    general = {
        allow_tearing = true,
        gaps_in = 2,
        snap = {
            border_overlap = true,
            enabled = true,
            respect_gaps = true,
            window_gap = 5,
        },
    },
    input = {
        follow_mouse = 1,
        mouse_refocus = true,
        natural_scroll = true,
    },
    misc = {
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
        vrr = 0,
    },
    xwayland = {
        use_nearest_neighbor = false,
    },
})

-- Bezier curves
hl.curve("ease", { type = "bezier", points = { {0.25, 0.1}, {0.25, 1.0} } })

-- Animations
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5.0,
    bezier = "ease",
    style = "slidevert",
})

-- Keybinds
hl.unbind("SUPER + SHIFT + ESCAPE")
hl.bind("SUPER + SHIFT + ESCAPE", hl.dsp.exec_cmd("noctalia msg panel-toggle arrifat346afs/systempulse:panel"))
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.workspace.toggle_special("Games"))
hl.unbind("SUPER + SHIFT + G")
hl.bind("SUPER + SHIFT + G", hl.dsp.window.move({ workspace = "special:Games" }))
