-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:Acer Technologies XF243Y P 0x206122C3",
  mode = "1920x1080@165.003",
  position = "0x0",
  scale = 1,
  vrr = 1,
  cm = "hdr",
  sdrbrightness = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "SUNSHINE",
  mode = "2560x1664@60",
  position = "-2560x1080",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
