-- Generated by nwg-displays on 2026-07-31 at 09:03:35. Do not edit manually.

hl.monitor({
    output = "desc:Acer Technologies XF243Y P 0x206122C3",
    mode = "1920x1080@165.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
