-- Generated by Noctalia

local primary = "rgb(e1e2d5)"
local surface = "rgb(1d1b1d)"
local secondary = "rgb(2d2a2e)"
local error = "rgb(d94a59)"

local function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = primary,
                inactive_border = surface,
            },
        },

        group = {
            col = {
                border_active = secondary,
                border_inactive = surface,
                border_locked_active = error,
                border_locked_inactive = surface,
            },

            groupbar = {
                col = {
                    active = secondary,
                    inactive = surface,
                    locked_active = error,
                    locked_inactive = surface,
                },
            },
        },
    })
end

return {
    colors = {
        primary = primary,
        surface = surface,
        secondary = secondary,
        error = error,
    },
    apply_theme = apply_theme
}
