color0 #1b2436
color1 #fd4663
color2 #6791e4
color3 #705cd6
color4 #aa66cc
color5 #93b1ec
color6 #a396e9
color7 #f2f2f3
color8 #606774
color9 #fd4663
color10 #6791e4
color11 #705cd6
color12 #aa66cc
color13 #93b1ec
color14 #a396e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #141b29
background            #141b29
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #1b2436
active_border_color   #6791e4
inactive_border_color #1b2436
url_color             #6791e4

active_tab_foreground   #181d25
active_tab_background   #6791e4
inactive_tab_foreground #afb1b6
inactive_tab_background #1b2436
cursor_trail_color      #afb1b6
