color0 #1a2437
color1 #fd4663
color2 #6790e4
color3 #8271ec
color4 #ab66cc
color5 #93b0ec
color6 #a396e9
color7 #f2f2f3
color8 #616771
color9 #fd4663
color10 #6790e4
color11 #8271ec
color12 #ab66cc
color13 #93b0ec
color14 #a396e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #141b2a
background            #141b2a
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #1a2437
active_border_color   #6790e4
inactive_border_color #1a2437
url_color             #6790e4

active_tab_foreground   #181c25
active_tab_background   #6790e4
inactive_tab_foreground #afb1b6
inactive_tab_background #1a2437
cursor_trail_color      #afb1b6
