color0 #182b39
color1 #fd4663
color2 #67c3e4
color3 #6481df
color4 #8f75dc
color5 #93d4ec
color6 #96a9e9
color7 #f2f3f3
color8 #5f6b6f
color9 #fd4663
color10 #67c3e4
color11 #6481df
color12 #8f75dc
color13 #93d4ec
color14 #96a9e9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #12202b
background            #12202b
foreground            #f2f3f3
selection_foreground  #afb4b6
selection_background  #182b39
active_border_color   #67c3e4
inactive_border_color #182b39
url_color             #67c3e4

active_tab_foreground   #182125
active_tab_background   #67c3e4
inactive_tab_foreground #afb4b6
inactive_tab_background #182b39
cursor_trail_color      #afb4b6
