[general]
font-sans = "Times New Roman"
font-mono = "JetBrains Mono NL"
tearing-mode = true

[bar]
scale = 1.0
bg = "transparent"
border-color = "bg-active"
rounding = "lg"
button-variant = "basic"
button-rounding = "lg"
button-border-location = "top"
button-border-width = 0
button-group-opacity = 0
button-group-border-color = "transparent"
button-group-rounding = "full"
dropdown-shadow = false

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "clock",
    "weather",
    "separator",
    "media",
    "cava",
]
right = [
    "network",
    "bluetooth",
    "volume",
    "notifications",
]

[[bar.layout.center]]
name = "Windows"
modules = [
    "hyprland-workspaces",
    "window-title",
]

[styling]
rounding = "lg"
theming-monitor = "DLP-1"

[styling.palette]
bg = "#11111b"
surface = "#181825"
elevated = "#1e1e2e"
fg = "#cdd6f4"
fg-muted = "#bac2de"
primary = "#b4befe"
red = "#f38ba8"
yellow = "#f9e2af"
green = "#a6e3a1"
blue = "#74c7ec"

[modules.cava]
direction = "mirror"

[modules.clock]
dropdown-show-seconds = true

[modules.hyprland-workspaces]
label-use-name = true

[modules.media]
icon-type = "spinning-disc"

[modules.notifications]
blocklist = ["HyDE Notify"]
popup-urgency-bar = "critical"

[modules.separator]
color = "fg-default"

[wallpaper]
transition-type = "center"
transition-duration = 0.4000000059604645
