[general]
font-sans = "Times New Roman"
font-mono = "JetBrains Mono NL"

[bar]
bg = "transparent"
border-color = "bg-active"
button-border-location = "top"
button-border-width = 0
button-group-opacity = 0
button-group-rounding = "full"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "clock",
    "weather",
    "separator",
    "media",
    "cava",
]
right = [
    "bluetooth",
    "volume",
    "notifications",
]

[[bar.layout.center]]
name = "Windows"
modules = [
    "hyprland-workspaces",
    "window-title",
]

[styling]
theming-monitor = "DLP-1"

[modules.cava]
direction = "mirror"

[modules.clock]
dropdown-show-seconds = true

[modules.hyprland-workspaces]
label-use-name = true

[modules.media]
icon-type = "spinning-disc"

[modules.notification]
border-show = true
blocklist = ["HyDE Notify"]
popup-urgency-bar = "critical"
